import type { SparkEconConfig, SparkPurchaseTier } from "@/types/sparks";

export const SPARK_CONFIG: SparkEconConfig = {
  lessonReward: 10,
  lessonRepeatReward: 5,
  lessonRepeatMaxRewards: 3,
  quizBaseReward: 5,
  quizPerCorrectBonus: 2,
  quizPerfectBonus: 5,
  streakBonusTable: { 7: 20, 14: 35, 21: 50, 30: 75 },
  weeklyMilestoneReward: 10,
  dailyEarnCap: 500,
  subscriberDailyEarnCap: 1000,
  subscriberMultiplier: 2,
  subscriberDailyBonus: 5,
  cooldownHours: 0,
  freeLessonsPerDay: Infinity,
  cooldownSkipCost: 25,
  streakFreezeCost: 50,
  startingBalance: 1000,
  coursePrices: {
    "web-fundamentals": 0,
    "react-literacy": 0,
    "claude-code": 0,
    "system-design": 0,
    "cfa-1": 0,
    "cfa-2": 0,
    "cfa-3": 0,
  },
  freeCourses: [
    "ai-fluency",
    "texas-holdem",
    "web-fundamentals",
    "react-literacy",
    "claude-code",
    "system-design",
    "cfa-1",
    "cfa-2",
    "cfa-3",
  ],
  diminishingReturnsThreshold: 3,
  diminishingReturnsMultiplier: 0.5,
};

export const PURCHASE_TIERS: SparkPurchaseTier[] = [
  { id: "starter", sparks: 50, priceUsd: 0.99, bonusSparks: 25, label: "Starter" },
  { id: "explorer", sparks: 300, priceUsd: 4.99, bonusSparks: 100, label: "Explorer" },
  { id: "adventurer", sparks: 700, priceUsd: 9.99, bonusSparks: 200, label: "Adventurer" },
  { id: "champion", sparks: 2000, priceUsd: 24.99, bonusSparks: 500, label: "Champion" },
  { id: "legend", sparks: 4500, priceUsd: 49.99, bonusSparks: 1000, label: "Legend" },
];
